## genes of interest for `r my_contrast_name`

```{r}
res_file <-
  file.path("intermediate_results",
            paste0(my_contrast_name, "_results.rds"))
res <- readRDS(res_file)

all_log2_fc <-
  get_all_log2fc(res, red_feature_annot, links = T)

# stopifnot(
#   all(genes_of_interest$feature_id %in% all_log2_fc$feature_id))
```


```{r results='asis'}
not_found <- !genes_of_interest$feature_id %in% all_log2_fc$feature_id
if (any(not_found)) {
  cat("The following genes of interest could not be found in the subset of protein coding genes") 
}
```


```{r}
if (any(not_found)) {
  genes_of_interest[not_found,] %>% knitr::kable()
}
```

The genes for which we have data can be found in the table below.

```{r}
gof_log2_fc <-
all_log2_fc %>%
dplyr::filter(feature_id %in% genes_of_interest$feature_id) 

gof_log2_fc %>%
  dplyr::mutate(feature_id = linked_feature_id) %>%
  dplyr::select(-linked_feature_id) %>%
  DT::datatable(rownames = F, escape = F)

gof_file_name <-
  file.path("tables/",
            paste0(my_contrast_name, "_features_of_interest.csv"))

gof_log2_fc %>%
  dplyr::select(-linked_feature_id) %>%
  write_csv(gof_file_name)
```

