
gdriveLinks:
  all: "",
  MS_Ribo_Proteome: https://drive.google.com/open?id=0BzvsY4eFxJIxM2g5c2E2LW9TSFU
  MS_Total_Proteome: https://drive.google.com/open?id=0BzvsY4eFxJIxcFhUdHNxMG13V1E
  RiboSeq_Ribo_Transcriptime: https://drive.google.com/open?id=0BzvsY4eFxJIxcFhUdHNxMG13V1E
  Total_Transcriptome: https://drive.google.com/open?id=0BzvsY4eFxJIxZHNiVDR2NWZIb1k
  tRNA-Microarray_Total_tRNAome: https://drive.google.com/open?id=0BzvsY4eFxJIxYlUtSEhEVHJfWDQ
  useful_datasets: https://drive.google.com/open?id=0BzvsY4eFxJIxbGN1ZEFfbENqYVE

  
results:
	threeDplotsfolder:	results/2017_5_24