
```{r }
################################################################################
########Load up the data from Mordret et al
################################################################################

knitr::opts_chunk$set(root.dir = here::here(),eval=FALSE,cache=FALSE,echo=FALSE,warning = FALSE,message = FALSE,include=FALSE)
isknitr<-isTRUE(getOption('knitr.in.progress'))
if(!isknitr){
	kggsave <- function(...){
		print(...)
		ggplot2::ggsave(...)
	}
	outfile<-rmarkdown::render(
		knitr::spin(here('src/R/Figures/fig2_mordret_data.R'),knit=F),
		output_dir=here('Reports'),
		knit_root_dir=here()
	)
	message(normalizePath(outfile))
	stop()

}


```
```{r setup, include=TRUE, echo=FALSE, eval=T}

ecolimistrans_df <- fread('ext_data/Mordret et al 2019/1-s2.0-S1097276519304988-mmc2.csv')
ecoli_AA_errordf <- ecolimistrans_df%>%filter(Media=='LB')%>%pluck('Origin AA')%>%table%>%{setNames(as.vector(.),names(.))}%>%enframe('AA','error_rate')%>%as.data.frame
ecoli_cod_errordf <- ecolimistrans_df%>%filter(Media=='LB')%>%pluck('Origin codon')%>%table%>%{setNames(as.vector(.),names(.))}%>%enframe('codon','error_rate')%>%as.data.frame
#
yeast_mistrans_df <- Sys.glob('ext_data/Mordret et al 2019/*mmc3.csv')%>%fread
yeast_AA_errordf <- yeast_mistrans_df%>%pluck('Origin AA')%>%table%>%{setNames(as.vector(.),names(.))}%>%enframe('AA','error_rate')%>%as.data.frame
yeast_cod_errordf <- yeast_mistrans_df%>%pluck('Origin codon')%>%table%>%{setNames(as.vector(.),names(.))}%>%enframe('codon','error_rate')%>%as.data.frame
#
stopifnot(! is(ecoli_cod_errordf$error_rate,'table'))
stopifnot(! is(yeast_cod_errordf$error_rate,'table'))

get_errorscatters<- function(tRNA_occ_df,errordf,col2plot){

	exportenv()
	tRNA_occ_df%>%
	left_join(errordf)%>%
	# filter(codon=='ATG')%>%
	mutate(timefrac = paste0(time,'_',fraction))%>%
	group_by(fraction,time)%>%
	nest%>%
	mutate(labl = paste0(
		'r = ',map_dbl(data,~cor(method='spearman',use='complete',.[[col2plot]],.$error_rate))%>%round(3),'\n',
		'p = ',map_dbl(data,~cor.test(method='spearman',use='complete',.[[col2plot]],.$error_rate)$p.value%>%round(3))
	))%>%
	unnest%>%
	{
	#	
		# labelpos = group_by(.,codon)%>%summarise(m_signal=mean(m_signal),error_rate=mean(error_rate))%>%
			# mutate(AA = GENETIC_CODE[codon]%>%qs('S+'))		
		# filter(codon%>%str_detect("ATG"))%>%
		ggplot(data=.,aes(x=error_rate,y=.[[col2plot]],color=time))+
		geom_point(size=1)+
		# geom_line(color=I('grey'))+
		facet_wrap(nrow=3,timefrac ~ . )+
		scale_color_manual(values=stagecols)+
		geom_text(show.legend=F,aes(label=codon,color=NULL),size=4)+
		geom_text(show.legend=F,data=distinct(.,timefrac,time,fraction,labl),hjust=0,vjust=1,x= -Inf,y=Inf,aes(label=labl))+
		# geom_text(show.legend=F,data=labelpos,aes(label=AA,color=NULL),size=9)+
		# geom_line(aes(group=qs(GENETIC_CODE[codon],'S+'),color=NULL),size=1,linetype=2)+
		geom_smooth(method='lm')+
		theme_bw()+
		scale_y_continuous(name=col2plot)+
		scale_x_log10(name='Error Rate')
	}
}
#
tRNA_occ_df$trna_signal <- tRNA_occ_df$signal
#
#plot with the AAs as colors
```
```{r plots, include=TRUE, echo=FALSE, eval=T,fig.height=12,fig.width=12}
plotfile<-'plots/figures/figure2/trna_codons/percodon_ecolierror_Riboocc.pdf'
kggsave(get_errorscatters(tRNA_occ_df,ecoli_cod_errordf,'occupancy'),file=plotfile,w=12,h=12)
normalizePath(plotfile)
#plot with the AAs as colors
plotfile<-'plots/figures/figure2/trna_codons/percodon_yeasterror_Riboocc.pdf'
kggsave(get_errorscatters(tRNA_occ_df,yeast_cod_errordf,'occupancy'),file=plotfile,w=12,h=12)
normalizePath(plotfile)
#plot with the AAs as colors
plotfile<-'plots/figures/figure2/trna_codons/percodon_ecolierror_tRNAsig.pdf'
kggsave(get_errorscatters(tRNA_occ_df,ecoli_cod_errordf,'trna_signal'),file=plotfile,w=12,h=12)
normalizePath(plotfile)
#plot with the AAs as colors
plotfile<-'plots/figures/figure2/trna_codons/percodon_yeasterror_tRNAsig.pdf'
kggsave(get_errorscatters(tRNA_occ_df,yeast_cod_errordf,'trna_signal'),file=plotfile,w=12,h=12)
normalizePath(plotfile)
#plot with the AAs as colors
plotfile<-'plots/figures/figure2/trna_codons/perAA_ecolierror_Riboocc.pdf'
kggsave(get_errorscatters(tRNA_occ_df,ecoli_AA_errordf,'occupancy'),file=plotfile,w=12,h=12)
normalizePath(plotfile)
#plot with the AAs as colors
plotfile<-'plots/figures/figure2/trna_codons/perAA_yeasterror_Riboocc.pdf'
kggsave(get_errorscatters(tRNA_occ_df,yeast_AA_errordf,'occupancy'),file=plotfile,w=12,h=12)
normalizePath(plotfile)
#plot with the AAs as colors
plotfile<-'plots/figures/figure2/trna_codons/perAA_ecolierror_tRNAsig.pdf'
kggsave(get_errorscatters(tRNA_occ_df,ecoli_AA_errordf,'trna_signal'),file=plotfile,w=12,h=12)
normalizePath(plotfile)
#plot with the AAs as colors
plotfile<-'plots/figures/figure2/trna_codons/perAA_yeasterror_tRNAsig.pdf'
kggsave(get_errorscatters(tRNA_occ_df,yeast_AA_errordf,'trna_signal'),file=plotfile,w=12,h=12)
normalizePath(plotfile)
```

Comparison of the mordret et al data to tRNA data
Comparison of the mordret et al data to A site occupancy data
Not sure if this should be a normalized somehow to account for likelihood of observing different subs. 
They seem to just ignore that

