---
title: "Report_cluto_clusts"
author: "Dermot Harnett"
date: "26/03/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE)
library(tidyverse)
library(magrittr)
library(data.table)
library(stringr)
library(magrittr)
library(splines)

load('~/projects/cortexomics/data/cluto_clusts.Rdata')
```

##Clusters - CLUTO, Transformed Expr Data

```{r Cluster trajectory plot,fig.width=12,fig.height=8,cache=F}
make_cluster_trajplots(clutoclustlist_filt[[13]]$cluster)
```

## GO term enrichment per cluster

```{r Go Enirched GO terms,results='asis'}

go_enrichmenttables <- list(
  goenrichmentsbp,
  goenrichmentsmf,
  goenrichmentscc
)%>%setNames(c('BP','MF','CC'))

ontlongs<-c('Biological Process','Molecular Function','Cellular Compartment')%>%setNames(c())

for(on in names(go_enrichmenttables)[T]){
  for(cluster in names(onttable[T])){
    onttable <- go_enrichmenttables[[ont]]
    ontlong <- ontlongs[ont]
    clusterletter <- LETTERS[as.numeric(cluster)]
    cat(str_interp('\n### ${ontlong} ; Cluster: ${clusterletter}'))
   # print(DT::datatable(onttable[[cluster]]%>%arrange(elimFisher)%>%head(20)))
    print(knitr::kable(onttable[[cluster]]%>%arrange(elimFisher)%>%filter(elimFisher<0.05)%>%head(20)))
   # cat(knitr::knit_child(text = knitr::knit_expand('knitr::kable(onttable[[cluster]])'),envir = globalenv(),quiet=T))
  }
}
```

##Clusters - Relationships by GO shared terms

```{r Go Enrichment Cladograms}

go_enrichmenttables <- list(
  goenrichmentsbp,
  goenrichmentsmf,
  goenrichmentscc
)%>%setNames(c('BP','MF','CC'))

for(ont in names(go_enrichmenttables)){
  goenrichments <- go_enrichmenttables[[ont]]
  godistmatrix <- goenrichments%>%
    map(.%>%mutate(Term = paste0(Term,GO.ID),issig = elimFisher<0.05)%>%
          select(Term,issig))%>%bind_rows(.id='cluster')%>%
    mutate(cluster = LETTERS[as.numeric(cluster)])%>%
    spread(cluster,issig)%>%
    map_df(replace_na,F)%>%
    {t(as.matrix(.[,-1]))}
  
  godistmatrix%>%
    dist('manhattan')%>%
    hclust%>%
    as.dendrogram%>%
    plot( cex = 0.2, horiz=TRUE, main = paste0('\nCLUTO clusters, distance by enriched GO terms :\n ',ont))
}

```
